### ISSUE TITLE
Refactor Face and Faces to Edge and EdgeGrid

### ISSUE THREAD

**Issue by tmcclintock** [tmcclintock/donjuan#34]
Right now the `Face` class represents a single face of a `Cell`, which has a `Faces` attribute. The idea is that we can put things on each face (like generated wall details) and find walls based on the faces. The downsize is that at present, since the `Cell` is composed of the `Faces`, a `Face` doesn't know about the `Face` of an adjoining cell directly. It can only be found when the `Cell` is part of a `Grid`. This also means that the faces of the cells take up 2X as much memory as they need to (since two `Face` objects represent the same thing).

This issue proposes a refactor by eliminating the `Face` class and replacing it with the `Edge` class. Like the `Cell` class, the `Edge` class exists in a grid called an `EdgeGrid`. If a `SquareGrid` is `N` by `M` in area then the horizontal edge grid would be `N+1` by `M` while the vertical edge grid would be `N` by `M+1`. Horizontal edges could have `cell_above` and `cell_below` attributes, while vertical edges could have `cell_left` and `cell_right` attributes. `SquareCell` could have `edge_above`, `edge_below`, `edge_left`, and `edge_right` attributes.

The obvious downside is that the `HexEdgeGrid` becomes more complicated (but may not more complicated than it already was with `Faces`?).

Use this issue as a discussion, and replace it later with an actual specification.

**Comment by tmcclintock** [comment]
For a `HexGrid` that was `N` by `M` in size, the `HexEdgeGrid` for horizontal edges would also be `N+1` by `M`. The "/" edge grid would also be this size, and so would the edge grid for the "\" edges.

**Comment by jammcc** [comment]
👍 This makes sense to me, I had been thinking along the same lines
