### ISSUE TITLE
Switch from Travis CI to Github

### ISSUE THREAD

**Issue by tmcclintock** [tmcclintock/donjuan#37]
Travis doesn't support open source CI/CD indefinitely now, and they are asking me for money. We should move off of travis and switch to [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/guides/about-continuous-integration).

This should be high priority.

**Comment by jammcc** [comment]
Added the workflow https://github.com/tmcclintock/donjuan/blob/main/.github/workflows/python-app.yml
It looks like it'll need some tweaking to flake correctly https://github.com/tmcclintock/donjuan/runs/1651960055?check_suite_focus=true
Or we could have it not flake, if we're banking on everyone always running pre-commit.


To remove travis, is that just a matter of deleting the .travis.yml file?

**Comment by tmcclintock** [comment]
I'm fine not running flake8 in an action, and just doing it locally.

Yes, we delete the travis file and I'll unhook it manually on their site.

**Comment by tmcclintock** [comment]
I have uninstalled Travis from my projects, so deleting the `.travis.yml` file should be enough now.

**Comment by jammcc** [comment]
I commented out the flake8, looks like we need a token set for coveralls to work https://github.com/tmcclintock/donjuan/runs/1654259142?check_suite_focus=true

**Comment by tmcclintock** [comment]
Weird. Not sure what that means. Will investigate tomorrow.

**Comment by tmcclintock** [comment]
@jammcc finished this and we are good.
