### ISSUE TITLE
Detect continuous walls/delete faces

### ISSUE THREAD

**Issue by tmcclintock** [tmcclintock/donjuan#4]
The [`Cell`](https://donjuan.readthedocs.io/en/latest/autoapi/donjuan/cell/index.html) class has a [`Faces`](https://donjuan.readthedocs.io/en/latest/autoapi/donjuan/face/index.html#donjuan.face.Faces) class attached to it for all the faces of the cell (4 faces for a square cell, 6 for a hexagonal cell). However, if two cells are adjacent in a [`Grid`](https://donjuan.readthedocs.io/en/latest/autoapi/donjuan/grid/index.html) then the adjoining faces should be deleted/ignored in some way (maybe we need a `IgnoredFace` class or something).

An algorithm (some implementation of DFS/BFS) must be devised to loop over the cells in the `Grid` and detect only the walls facing an empty space.

This issue requires the following steps to complete:

- [ ] Use the dummy dungeon to create a `Grid` where the `Cell`s inside are filled according to the dummy. The dummy dungeon (from #3) is:
```python
dungeon = [
    [1, 1, 1, 0, 1],
    [1, 1, 1, 0, 1],
    [1, 1, 1, 0, 0],
    [1, 1, 1, 0, 1],
    [1, 1, 1, 0, 1]
]
```
- [ ] write either a new class, or a method attached to the `Grid` or `Dungeon` to detect outer walls and store them somehow

**Comment by tmcclintock** [comment]
@jammcc I made the `wall_finder` branch where I declared the `WallFinder` class. Can you move your work into that?

**Comment by jammcc** [comment]
@tmcclintock figure we can close this issue? It seems outdated, and the "implementation" will be a pretty trivial component of the export process I think.

**Comment by tmcclintock** [comment]
Yup.
