### ISSUE TITLE
Create class for interacting with the random package

### ISSUE THREAD

**Issue by tmcclintock** [tmcclintock/donjuan#8]
The [`random`](https://docs.python.org/3/library/random.html) package is in the Python standard library, which will will use within the `Randomizer` (see #6). We should have a thin wrapper class around `random` to allow us to set the [RNG seed](https://docs.python.org/3/library/random.html#random.seed). This will make it so that in the future when donjuan is called from an external source (like FoundryVTT or a webserver) there will be an interface for setting the seed.

**Comment by jammcc** [comment]
Closing as we will instead have the Randomizer class have "seed" as an optional argument.
